Revert shellcheck changes (#58)
Un-breaking the build (sorry @pdewilde). Apparently the default version
of shellcheck installed on the runners is too old and [doesn't have the
`--rcfile`
flag](https://github.com/abcxyz/infra-github/actions/runs/14722558591/job/41319131134?pr=196).
We didn't catch this in presubmits because that codepath isn't executed.

```text
Run # Create a unique output file outside of the checkout.
Notice: Wrote configuration file to /home/runner/work/_temp/9d14b[43](https://github.com/abcxyz/infra-github/actions/runs/14722558591/job/41319131134?pr=196#step:6:45).shellcheckrc
Run find "${TARGET}" \( -type f -name '*.sh' -or -name '*.bash' -or -name '*.zsh' \) -exec \
unrecognized option `--rcfile=/home/runner/work/_temp/9d14b43.shellcheckrc'

Usage: shellcheck [OPTIONS...] FILES...
  -a                  --check-sourced            Include warnings from sourced files
  -C[WHEN]            --color[=WHEN]             Use color (auto, always, never)
  -i CODE1,CODE2..    --include=CODE1,CODE2..    Consider only given types of warnings
  -e CODE1,CODE2..    --exclude=CODE1,CODE2..    Exclude types of warnings
  -f FORMAT           --format=FORMAT            Output format (checkstyle, diff, gcc, json, json1, quiet, tty)
                      --list-optional            List checks disabled by default
                      --norc                     Don't look for .shellcheckrc files
  -o check1,check2..  --enable=check1,check2..   List of optional checks to enable (or 'all')
  -P SOURCEPATHS      --source-path=SOURCEPATHS  Specify path when looking for sourced files ("SCRIPTDIR" for script's dir)
  -s SHELLNAME        --shell=SHELLNAME          Specify dialect (sh, bash, dash, ksh)
  -S SEVERITY         --severity=SEVERITY        Minimum severity of errors to consider (error, warning, info, style)
  -V                  --version                  Print version information
  -W NUM              --wiki-link-count=NUM      The number of wiki links to show, when applicable
  -x                  --external-sources         Allow 'source' outside of FILES
                      --help                     Show this usage summary and exit

Error: Process completed with exit code 1.
```

![CleanShot 2025-04-28 at 23 28
40@2x](https://github.com/user-attachments/assets/a39038dc-abba-4a74-9b45-58f9353f91af)